export const actionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    SET_SEARCHED_PRODUCTS: "SET_SEARCHED_PRODUCTS",
    SET_QUERY: "SET_QUERY",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    ADD_PRODUCT: "ADD_PRODUCT",
    SUBSTRACT_PRODUCT: "SUBSTRACT_PRODUCT",
    REOMOVE_PRODUCT_FROM_CART: "REOMOVE_PRODUCT_FROM_CART",
    REMOVE_PRODUCTS_FROM_CART: "REMOVE_PRODUCTS_FROM_CART",
}